<%--
  功能描述 ：当前充值员售卡信息
  
  Author : wangjian
  Date   : 2014-03-03
  Version: 1.0
--%>
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
	<div class="row">
		<div class="col-md-12">
			<div class="note note-info alert alert-info">
				<i class="fa fa-hand-o-right"></i>
				&nbsp;&nbsp;&nbsp;今天还没有结算！
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
			</div>
		</div>
	</div>