<%--
  功能描述 ：公共头文件
  
  Author : wangjian
  Date   : 2014-03-03
  Version: 1.0
--%>
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
			<div class="col-md-12 column sortable">
				<div class="portlet box red">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-tasks"></i>
							发卡充值信息&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<span class="bg-red">当前授权余额：10000.00</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<span class="bg-red">总收入金额：20000.00</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<span class="bg-red">总支出金额：8000.00</span>
						</div>
						<div class="tools">
							<button type="button" class="btn btn-default btn-sm" role="button">
								<i class="fa fa-print"></i>&nbsp;&nbsp;&nbsp;打印&nbsp;&nbsp;&nbsp;
							</button>							
							<a href="javascript:;" class="collapse"></a>
							<a href="javascript:;" class="reload"></a>
							<a href="javascript:;" class="remove"></a>
						</div>
					</div>
					<div class="portlet-body">
						<div class="table-responsive">
							<table class="table table-hover">
								<tbody>
									<tr>
										<td><span class="btn dark btn-block">售卡张数：500</span></td>
										<td><span class="btn default btn-block">钱包充值张数：1000</span></td>
										<td><span class="btn dark btn-block">充值撤销张数：10000</span></td>
										<td><span class="btn default btn-block">补卡张数：300</span></td>
										<td><span class="btn dark btn-block">挂失张数：200</span></td>
										<td><span class="btn default btn-block">有卡销户张数：100</span></td>
										<td><span class="btn dark btn-block">无卡销户张数：150</span></td>
									</tr>
									<tr>
										<td><span class="btn dark btn-block">售卡收费金额：20000.00</span></td>
										<td><span class="btn default btn-block">钱包充值金额：1000.000</span></td>
										<td><span class="btn dark btn-block">充值撤销金额：2000.00</span></td>
										<td><span class="btn default btn-block">领取冻结金额：3000.90</span></td>
										<td><span class="btn dark btn-block">解挂张数：200</span></td>
										<td><span class="btn default btn-block">有卡销户金额：3000..0</span></td>
										<td><span class="btn dark btn-block">无卡销户金额：1500.00</span></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>